name: flutter_starter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  # Flutter SDK & Localization
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Flutter UI Components
  cupertino_icons: ^1.0.8

  # Dependency Management 
  get_it: ^8.0.3
  path_provider: ^2.1.5

  # Networking
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  internet_connection_checker_plus: ^2.7.2
  connectivity_plus: ^6.1.4
  pretty_dio_logger: ^1.4.0

  # Utilities
  logger: ^2.5.0
  flutter_native_splash: ^2.4.6
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  path: ^1.9.1

  # Storages
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  drift: ^2.26.1
  drift_flutter: ^0.2.4

  # Model and Code Gen
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # State Management
  flutter_bloc: ^9.1.1

  # Navigation and Routing
  go_router: ^15.1.2

  # Firebase
  firebase_core: ^3.13.0
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.3.5
  firebase_messaging: ^15.2.5

dev_dependencies:
  # Code generation
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  drift_dev: ^2.26.1
  retrofit_generator: ^9.2.0
  flutter_gen_runner: ^5.10.0

  # Testing
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  mockito: ^5.4.6
  integration_test:
    sdk: flutter

  # Linting & tools
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/.env